# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# more docs at https://github.com/jameshamann/jekyll-material-theme
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Von Innen nach Aussen transformieren
name: Miriam & Markus Schmidberger
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Alles beginnt in unserem Innersten. Für erfolgreiche Transformationen müssen
  wir den tiefsten Kern finden und dann nach Aussen wandern. Hier teilen wir
  unsere Innen nach Aussen Transformationswege und begleiten Sie gerne bei
  Ihren Prozessen.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll



parallax_image_one: assets/images/caterpillar.jpg # These are the images used for the parallax background
parallax_image_two: assets/images/butterfly.jpg



# Settings for the porfolio section
portfolio_heading: Unser Transformation Portfolio
portfolio_type: cards #cards or carousel

project_button: more #Github

project_one: Das Transformations Netzwerk
project_one_description: Describe your project!
project_one_url: /transformation/
project_one_icon: location_on # these are from materiailize css, the full collection is here: http://materializecss.com/icons.html

project_two: Cloud & BigData & Agile Business Transformation
project_two_description: Describe your project!
project_two_url: https://github.com/jameshamann/jekyll-material-theme
project_two_icon: photo_camera

project_three: Bewusstes Eltern Sein
project_three_description: Describe your project!
project_three_url: https://github.com/jameshamann/jekyll-material-theme
project_three_icon: hotel

project_four: Yoga zur Transformation
project_four_description: Describe your project!
project_four_url: https://github.com/jameshamann/jekyll-material-theme
project_four_icon: restaurant

cookie_accept_message: Thanks! # The pop-up dialog that appears after accepting the cookie notice.
syntax_highlighting: true # include the css for syntax highlighting

# Build settings
markdown: kramdown
# theme: jekyll-material-theme
remote_theme: jameshamann/jekyll-material-theme
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-minifier

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
